# year index
# inspect element -> copy full xpath
# /html/body/div[3]/div/div[1]/form/div[3]/div[1]/div[2]/div[1]/div/select/option[2], in 2023-09-30
# /html/body/div[3]/div/div[1]/form/div[3]/div[1]/div[2]/div[1]/div/select/option[24], in 2023-09-30
ano_ini_index: 2
ano_fim_index: 17

# police station index
# inspect element -> copy full xpath
# /html/body/div[3]/div/div[1]/form/div[3]/div[1]/div[2]/div[1]/div/select/option[2], in 2023-09-30
# /html/body/div[3]/div/div[1]/form/div[3]/div[1]/div[2]/div[1]/div/select/option[24], in 2023-09-30
del_ini_index: 2
del_fim_index: 120